# Generated by specgen.py ryanabx

# Generated by rust2rpm 25

# prevent library files from being installed

%global crate cosmic-icons
%global repo https://github.com/pop-os/cosmic-icons

Name:           cosmic-icons
Version:        # TO BE REPLACED AUTOMATICALLY

Release:        %autorelease
Summary:        System76 Cosmic icon theme for Linux

License:        CC-BY-SA-4.0

URL:            https://github.com/pop-os/cosmic-icons
Source:         %{crate}.tar.gz


# For now, we require all deps for all of cosmic-epoch
BuildRequires:  make
BuildRequires:  which
BuildRequires:  just
BuildRequires:  rustc
BuildRequires:  libglvnd-devel
BuildRequires:  libseat-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  lld
BuildRequires:  libinput-devel
BuildRequires:  glib2-devel
BuildRequires:  gtk3-devel
BuildRequires:  dbus-devel
BuildRequires:  wayland-devel
BuildRequires:  clang-devel
BuildRequires:  cargo
BuildRequires:  mesa-libgbm-devel
BuildRequires:  pipewire-devel
BuildRequires:  pam-devel
BuildRequires:  flatpak-devel
BuildRequires:  rust-rav1e+nasm-rs-devel



# For now, we require all deps for all of cosmic-epoch
Requires:       libseat
Requires:       pop-icon-theme
Requires:       greetd
Requires:       greetd-selinux
Requires:       cage
Requires:       mozilla-fira-mono-fonts
Requires:       mozilla-fira-sans-fonts


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-icons

%build
echo done

%install
just rootdir=%{buildroot} install

%files

%{_datadir}/icons/Cosmic/scalable/*


%changelog
%autochangelog
    