# Generated by specgen.py ryanabx
%define debug_package %{nil}
# Generated by rust2rpm 25

# prevent library files from being installed

%global crate cosmic-icons
%global repo https://github.com/pop-os/cosmic-icons

Name:           cosmic-icons
Version:        # TO BE REPLACED AUTOMATICALLY

Release:        %autorelease
Summary:        System76 Cosmic icon theme for Linux

License:        CC-BY-SA-4.0

URL:            https://github.com/pop-os/cosmic-icons
Source:         %{crate}.tar.gz


# For now, we require all deps for all of cosmic-epoch
BuildRequires:  make
BuildRequires:  which
BuildRequires:  just
BuildRequires:  rustc
BuildRequires:  pkgconfig(libglvnd)
BuildRequires:  pkgconfig(libseat)
BuildRequires:  pkgconfig(libxkbcommon)
BuildRequires:  lld
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(glib2)
BuildRequires:  pkgconfig(gtk3)
BuildRequires:  pkgconfig(dbus)
BuildRequires:  pkgconfig(wayland)
BuildRequires:  pkgconfig(clang)
BuildRequires:  cargo
BuildRequires:  pkgconfig(mesa-libgbm)
BuildRequires:  pkgconfig(pipewire)
BuildRequires:  pkgconfig(pam)
BuildRequires:  pkgconfig(flatpak)
BuildRequires:  pkgconfig(rust-rav1e+nasm-rs)
BuildRequires:  libappstream-glib



# For now, we require all deps for all of cosmic-epoch
Requires:       libseat
Requires:       pop-icon-theme
Requires:       greetd
Requires:       greetd-selinux
Requires:       cage
Requires:       mozilla-fira-mono-fonts
Requires:       mozilla-fira-sans-fonts


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cosmic-icons

%build
echo done

%install
just rootdir=%{buildroot} install

%files

%{_datadir}/icons/Cosmic/scalable/*
%{_datadir}/icons/Cosmic/index.theme


%changelog
%autochangelog
    