import cosmic_apps

def make_spec(specinfo):
    spec = f"""
# Generated by specgen.py ryanabx
{specinfo["globals"]}
# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
%global __cargo_is_lib() 0

%global crate {specinfo["name"]}
%global repo {specinfo["repo"]}

Name:           {specinfo["name"]}
Version:        # TO BE REPLACED AUTOMATICALLY

Release:        %autorelease
Summary:        {specinfo["summary"]}

License:        {specinfo["license"]}

URL:            {specinfo["repo"]}
{specinfo["sources"]}

{specinfo["buildrequires"]}

{specinfo["requires"]}

%global _description %{{expand:
%{{summary}}.}}

%description %{{_description}}

%prep
{specinfo["prep"]}

%build
{specinfo["build"]}

%install
{specinfo["install"]}

%files
{specinfo["files"]}

%changelog
%autochangelog
    """

    with open(f'{specinfo["name"]}.spec', 'w') as f:
        f.write(spec)

make_spec(cosmic_apps.COSMIC_APP_LIBRARY)
