name: make_rpm

# Were we can define the inputs that our action will accept
inputs:
  name:
    required: true
  version: 
    required: true

runs:
  using: "composite"
  steps:
  - name: "Install dependencies and rpm dev tools"
    run: |
      sudo dnf install -y rpmdevtools rpmlint
      sudo dnf install -y git make which just rustc libglvnd-devel libseat-devel libxkbcommon-devel lld libinput-devel glib2-devel gtk3-devel dbus-devel wayland-devel clang-devel cargo mesa-libgbm-devel pipewire-devel pam-devel flatpak-devel rust-rav1e+nasm-rs-devel
    shell: bash
  - name: Build rpm
    run: |
      rpmdev-setuptree
      cp specfiles/$NAME.spec ~/rpmbuild/SPECS
      spectool -g -R -S ~/rpmbuild/SPECS/$NAME.spec
      rpmbuild -bb ~/rpmbuild/SPECS/$NAME.spec
    shell: bash
    env:
      NAME: ${{ inputs.name }}
  - uses: actions/upload-artifact@v4
    with:
      # Name of the artifact to upload.
      # Optional. Default is 'artifact'
      name: ${{inputs.name}}
      # A file, directory or wildcard pattern that describes what to upload
      # Required.
      path: ~/rpmbuild/RPMS/x86_64/${{inputs.name}}-${{inputs.version}}-1.fc39.x86_64.rpm
      # If true, an artifact with a matching name will be deleted before a new one is uploaded.
      # If false, the action will fail if an artifact for the given name already exists.
      # Does not fail if the artifact does not exist.
      # Optional. Default is 'false'
      overwrite: true