
# Generated by specgen.py ryanabx

%global appid com.system76.CosmicAppLibrary

# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
%global __cargo_is_lib() 0

%global crate cosmic-app-library
%global repo https://github.com/pop-os/cosmic-applibrary

Name:           cosmic-app-library
Version:        # TO BE REPLACED AUTOMATICALLY

Release:        %autorelease
Summary:        A boilerplate template to get started with GTK, Rust, Meson, Flatpak, Debian made for Cosmic.

License:        GPL-3.0

URL:            https://github.com/pop-os/cosmic-applibrary

Source:         %{crate}.tar.gz
Source:         %{crate}-vendor.tar.xz



# For now, we require all deps for all of cosmic-epoch
BuildRequires:  make
BuildRequires:  which
BuildRequires:  just
BuildRequires:  rustc
BuildRequires:  libglvnd-devel
BuildRequires:  libseat-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  lld
BuildRequires:  libinput-devel
BuildRequires:  glib2-devel
BuildRequires:  gtk3-devel
BuildRequires:  dbus-devel
BuildRequires:  wayland-devel
BuildRequires:  clang-devel
BuildRequires:  cargo
BuildRequires:  mesa-libgbm-devel
BuildRequires:  pipewire-devel
BuildRequires:  pam-devel
BuildRequires:  flatpak-devel
BuildRequires:  rust-rav1e+nasm-rs-devel



# For now, we require all deps for all of cosmic-epoch
Requires:       libseat
Requires:       pop-icon-theme
Requires:       greetd
Requires:       greetd-selinux
Requires:       cage
Requires:       mozilla-fira-mono-fonts
Requires:       mozilla-fira-sans-fonts


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep

%autosetup -n %{crate} -p1 -a1
cat .vendor/config.toml > .cargo/config


%build

cargo build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}


%install

%{_bindir}/cosmic-app-library
%{_datadir}/applications/com.system76.CosmicAppLibrary.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppLibrary.svg
%{_datadir}/metainfo/com.system76.CosmicAppLibrary.metainfo.xml



%files

%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md


install -Dm0644 target/release/cosmic-app-library %{_bindir}/cosmic-app-library
install -Dm0644 /data/com.system76.CosmicAppLibrary.desktop %{_datadir}/applications/com.system76.CosmicAppLibrary.desktop
install -Dm0644 /data/icons/com.system76.CosmicAppLibrary.svg %{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppLibrary.svg
install -Dm0644 /data/com.system76.CosmicAppLibrary.metainfo.xml %{_datadir}/metainfo/com.system76.CosmicAppLibrary.metainfo.xml



%changelog
%autochangelog
    