# Generated by specgen.py ryanabx

# Generated by rust2rpm 25

# prevent library files from being installed

%global crate cosmic-applets
%global repo https://github.com/pop-os/cosmic-applets

Name:           cosmic-applets
Version:        # TO BE REPLACED AUTOMATICALLY

Release:        %autorelease
Summary:        WIP applets for cosmic-panel

License:        GPL-3.0

URL:            https://github.com/pop-os/cosmic-applets

Source:         %{crate}.tar.gz
Source:         %{crate}-vendor.tar.xz



# For now, we require all deps for all of cosmic-epoch
BuildRequires:  make
BuildRequires:  which
BuildRequires:  just
BuildRequires:  rustc
BuildRequires:  libglvnd-devel
BuildRequires:  libseat-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  lld
BuildRequires:  libinput-devel
BuildRequires:  glib2-devel
BuildRequires:  gtk3-devel
BuildRequires:  dbus-devel
BuildRequires:  wayland-devel
BuildRequires:  clang-devel
BuildRequires:  cargo
BuildRequires:  mesa-libgbm-devel
BuildRequires:  pipewire-devel
BuildRequires:  pam-devel
BuildRequires:  flatpak-devel
BuildRequires:  rust-rav1e+nasm-rs-devel



# For now, we require all deps for all of cosmic-epoch
Requires:       libseat
Requires:       pop-icon-theme
Requires:       greetd
Requires:       greetd-selinux
Requires:       cage
Requires:       mozilla-fira-mono-fonts
Requires:       mozilla-fira-sans-fonts


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep

%autosetup -n %{crate}
mv ../%{crate}-vendor.tar.xz vendor.tar.xz
ls -a
mkdir -p .cargo
cp .vendor/config.toml .cargo/config.toml


%build

cargo build --bin cosmic-app-list
cargo build --bin cosmic-applet-audio
cargo build --bin cosmic-applet-battery
cargo build --bin cosmic-applet-bluetooth
cargo build --bin cosmic-applet-graphics
cargo build --bin cosmic-applet-network
cargo build --bin cosmic-applet-notifications
cargo build --bin cosmic-applet-power
cargo build --bin cosmic-applet-time
cargo build --bin cosmic-applet-tiling
cargo build --bin cosmic-applet-status-area
cargo build --bin cosmic-applet-workspaces
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}


%install
just rootdir=%{buildroot} prefix=%{_prefix} install

%files




%{_bindir}/cosmic-app-list
%{_datadir}/applications/com.system76.CosmicAppList.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppList.svg

%{_bindir}/cosmic-applet-audio
%{_datadir}/applications/com.system76.CosmicAppletAudio.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletAudio.svg

%{_bindir}/cosmic-applet-battery
%{_datadir}/applications/com.system76.CosmicAppletBattery.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletBattery.svg

%{_bindir}/cosmic-applet-bluetooth
%{_datadir}/applications/com.system76.CosmicAppletBluetooth.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletBluetooth.svg

%{_bindir}/cosmic-applet-graphics
%{_datadir}/applications/com.system76.CosmicAppletGraphics.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletGraphics.svg

%{_bindir}/cosmic-applet-network
%{_datadir}/applications/com.system76.CosmicAppletNetwork.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletNetwork.svg

%{_bindir}/cosmic-applet-notifications
%{_datadir}/applications/com.system76.CosmicAppletNotifications.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletNotifications.svg

%{_bindir}/cosmic-applet-power
%{_datadir}/applications/com.system76.CosmicAppletPower.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletPower.svg

%{_bindir}/cosmic-applet-time
%{_datadir}/applications/com.system76.CosmicAppletTime.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletTime.svg

%{_bindir}/cosmic-applet-tiling
%{_datadir}/applications/com.system76.CosmicAppletTiling.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletTiling.svg

%{_bindir}/cosmic-applet-status-area
%{_datadir}/applications/com.system76.CosmicAppletStatusArea.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletStatusArea.svg

%{_bindir}/cosmic-applet-workspaces
%{_datadir}/applications/com.system76.CosmicAppletWorkspaces.desktop
%{_datadir}/icons/hicolor/scalable/apps/com.system76.CosmicAppletWorkspaces.svg



%changelog
%autochangelog
    