# Generated by specgen.py ryanabx

# Generated by rust2rpm 25

# prevent library files from being installed

%global crate pop-launcher
%global repo https://github.com/pop-os/launcher

Name:           pop-launcher
Version:        # TO BE REPLACED AUTOMATICALLY

Release:        %autorelease
Summary:        Modular IPC-based desktop launcher service 

License:        GPL-3.0

URL:            https://github.com/pop-os/launcher

Source:         %{crate}.tar.gz
Source:         vendor.tar



# For now, we require all deps for all of cosmic-epoch
BuildRequires:  make
BuildRequires:  which
BuildRequires:  just
BuildRequires:  rustc
BuildRequires:  pkgconfig(libglvnd)
BuildRequires:  pkgconfig(libseat)
BuildRequires:  pkgconfig(libxkbcommon)
BuildRequires:  lld
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(glib2)
BuildRequires:  pkgconfig(gtk3)
BuildRequires:  pkgconfig(dbus)
BuildRequires:  pkgconfig(wayland)
BuildRequires:  pkgconfig(clang)
BuildRequires:  cargo
BuildRequires:  pkgconfig(mesa-libgbm)
BuildRequires:  pkgconfig(pipewire)
BuildRequires:  pkgconfig(pam)
BuildRequires:  pkgconfig(flatpak)
BuildRequires:  pkgconfig(rust-rav1e+nasm-rs)
BuildRequires:  libappstream-glib



# For now, we require all deps for all of cosmic-epoch
Requires:       libseat
Requires:       pop-icon-theme
Requires:       greetd
Requires:       greetd-selinux
Requires:       cage
Requires:       mozilla-fira-mono-fonts
Requires:       mozilla-fira-sans-fonts


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep

%autosetup -n %{crate} -p1
mv %{_sourcedir}/vendor.tar vendor.tar
ls -a
mkdir -p .cargo
cp .vendor/config.toml .cargo/config.toml


%build
just build-vendored

%install
install -Dm0755 target/release/pop-launcher-bin %{buildroot}/%{_bindir}/pop-launcher
#!/usr/bin/env sh
set -ex
for plugin in $('calc desktop_entries files find pop_shell pulse recent scripts terminal web cosmic_toplevel'); do
    dest=%{buildroot}/%{_prefix}/lib/pop-launcher/plugins/${plugin}
    mkdir -p ${dest}
    install -Dm0644 plugins/src/${plugin}/*.ron ${dest}
    ln -sf %{buildroot}/%{_bindir}/pop-launcher %{_prefix}/lib/pop-launcher/plugins/${plugin}/$(echo ${plugin} | sed 's/_/-/')
done
mkdir -p %{buildroot}/%{_prefix}/lib/pop-launcher/scripts/
for script in scripts/*; do
    cp -r ${script} %{buildroot}/%{_prefix}/lib/pop-launcher/scripts/
done


%files

%{_bindir}/pop-launcher
%{_prefix}/lib/pop-launcher/*


%changelog
%autochangelog
    