name: make_rpms
on:
  workflow_dispatch:

jobs:
  cosmic-applets:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-applets
          version: master
  cosmic-applibrary:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-applibrary
          version: master
  cosmic-bg:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-bg
          version: master
  cosmic-comp:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-comp
          version: master
  cosmic-edit:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-edit
          version: master
  cosmic-files:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-files
          version: master
  cosmic-greeter:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-greeter
          version: master
  cosmic-icons:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-icons
          version: master
  cosmic-launcher:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-launcher
          version: master
  cosmic-notifications:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-notifications
          version: master
  cosmic-osd:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-osd
          version: master
  cosmic-panel:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-panel
          version: master
  cosmic-randr:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-randr
          version: master
  cosmic-screenshot:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-screenshot
          version: master
  cosmic-session:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-session
          version: master
  cosmic-settings-daemon:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-settings-daemon
          version: master
  cosmic-settings:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-settings
          version: master
  cosmic-store:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-store
          version: master
  cosmic-term:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-term
          version: master
  cosmic-workspaces-epoch:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: cosmic-workspaces-epoch
          version: master
  xdg-desktop-portal-cosmic:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - uses: actions/checkout@v2
      - name: create rpm
        uses: "./.github/templates/make_rpm"
        with:
          name: xdg-desktop-portal-cosmic
          version: master
